import type { Product } from './store'

// Used only by `npm run dev:demo`. These are sample products, never an API fallback.
export const demoProducts: Product[] = [
  {
    productId: 1,
    name: 'The Daily Cream',
    brand: 'RadiantSkin',
    description:
      'A simple addition to your morning and evening routine. Take a moment, make it yours.',
    price: 245,
    stockQuantity: 12,
    volumeMl: 50,
    category: 'skin',
    imageUrl: '/images/studio-cream.jpg',
    instructions: 'Sample product information for the storefront preview.',
    reviews: [],
  },
  {
    productId: 2,
    name: 'Everyday Body Lotion',
    brand: 'RadiantSkin',
    description: 'Body care to make part of your everyday.',
    price: 189,
    stockQuantity: 8,
    volumeMl: 250,
    category: 'body',
    imageUrl: '/images/preview-lotion.svg',
    instructions: '',
    reviews: [],
  },
  {
    productId: 3,
    name: 'The Fresh Start Cleanser',
    brand: 'RadiantSkin',
    description: 'Start and end your day with a moment of care.',
    price: 165,
    stockQuantity: 18,
    volumeMl: 150,
    category: 'skin',
    imageUrl: '/images/preview-cleanser.svg',
    instructions: 'Sample product information for the storefront preview.',
    reviews: [],
  },
  {
    productId: 4,
    name: 'Daily Ritual Shampoo',
    brand: 'RadiantSkin',
    description: 'Make wash day a moment to look forward to.',
    price: 210,
    stockQuantity: 6,
    volumeMl: 300,
    category: 'hair',
    imageUrl: '/images/preview-shampoo.svg',
    instructions: '',
    reviews: [],
  },
  {
    productId: 5,
    name: 'The Body Butter',
    brand: 'RadiantSkin',
    description: 'Make space for a slower moment in your daily routine.',
    price: 275,
    stockQuantity: 0,
    volumeMl: 200,
    category: 'body',
    imageUrl: '/images/studio-cream.jpg',
    instructions: '',
    reviews: [],
  },
  {
    productId: 6,
    name: 'Everyday Conditioner',
    brand: 'RadiantSkin',
    description: 'The finishing touch to your hair care routine.',
    price: 220,
    stockQuantity: 2,
    volumeMl: 300,
    category: 'hair',
    imageUrl: '/images/preview-conditioner.svg',
    instructions: '',
    reviews: [],
  },
]
